name: Build and Deploy Production
on: [push, pull_request]

jobs:
    my_build:
      runs-on: ubuntu-latest
      steps:
        - name: checking out code
          uses: actions/checkout@master
        - name: install node
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'npm'

        - name: Process
          run: |
            echo "Production is running"
            npm install
            npm run package



